language: node_js
node_js:
  - "8"
dist: trusty
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - node_modules
addons:
  chrome: stable
script:
  - npm run lint
  - npm run test
before_install:
  - openssl aes-256-cbc -K $encrypted_849b15a310e0_key -iv $encrypted_849b15a310e0_iv -in client-secret.json.enc -out client-secret.json -d
install:
  - npm i
  - npm run build
before_deploy:
  - cd dist
deploy:
  provider: gae
  keyfile: "client-secret.json"
  project: "personal-website-233701"
