runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: personal-website/index.html
    upload: personal-website/index.html
    secure: never
    http_headers:
      Access-Control-Allow-Origin: '*'
  - url: /
    static_dir: personal-website
    secure: never
    http_headers:
      Access-Control-Allow-Origin: '*'

