runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: personal-website/index.html
    upload: personal-website/index.html
    secure: always
    redirect_http_response_code: 301
  - url: /
    static_dir: personal-website
    secure: always
    redirect_http_response_code: 301
