runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(?!dist)  # Skip any files not in the dist folder

handlers:
# Routing for bundles to serve directly
- url: /((?:runtime|main|polyfills|styles|vendor)\.[a-z0-9]+\.js)
  secure: never
  http_headers:
    Access-Control-Allow-Origin: '*'
  redirect_http_response_code: 301
  static_files: dist/personal-website/\1
  upload: dist/personal-website/.*

# Routing for bundle maps to serve directly
- url: /((?:runtime|main|polyfills|styles|vendor)\.[a-z0-9]+\.js\.map)
  secure: never
  http_headers:
    Access-Control-Allow-Origin: '*'
  redirect_http_response_code: 301
  static_files: dist/personal-website/\1
  upload: dist/personal-website/.*

# Routing for a prod styles.bundle.css to serve directly
- url: /(styles\.[a-z0-9]+\.css)
  secure: never
  http_headers:
    Access-Control-Allow-Origin: '*'
  redirect_http_response_code: 301
  static_files: dist/personal-website/\1
  upload: dist/personal-website/.*

# Routing for typedoc, assets, and favicon.ico to serve directly
- url: /((?:assets|docs)/.*|favicon\.ico)
  secure: never
  http_headers:
    Access-Control-Allow-Origin: '*'
  redirect_http_response_code: 301
  static_files: dist/personal-website/\1
  upload: dist/personal-website/.*

# Routing for service worker files serve directly
- url: /(manifest\.json|ngsw\.json|ngsw-worker\.js|safety-worker\.js|worker-basic\.min\.js|ngsw_worker\.es6\.js\.map)
  secure: never
  http_headers:
    Access-Control-Allow-Origin: '*'
  redirect_http_response_code: 301
  static_files: dist/personal-website/\1
  upload: dist/personal-website/.*

# Any other requests are routed to index.html for angular to handle so we don't need hash URLs
- url: /.*
  secure: never
  http_headers:
    Access-Control-Allow-Origin: '*'
  redirect_http_response_code: 301
  static_files: dist/personal-website/index.html
  upload: dist/personal-website/index\.html
