runtime: python27
api_version: 1
threadsafe: true
skip_files:
  - ^(?!dist)  # Skip any files not in the dist folder
handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: never
    http_headers:
      Access-Control-Allow-Origin: '*'
  - url: /
    static_dir: dist
    secure: never
    http_headers:
      Access-Control-Allow-Origin: '*'
